import type { ChatTheme } from '@/types';

export const imessageLight: ChatTheme = {
  id: 'imessage',
  name: 'iMessage',
  icon: '🍎',
  dark: false,
  vars: {
    chatBg: '#f2f2f7',
    headerBg: '#f2f2f7',
    headerText: '#000000',
    headerSubtext: '#8e8e93',
    myBubbleBg: '#007AFF',
    myBubbleText: '#ffffff',
    theirBubbleBg: '#e5e5ea',
    theirBubbleText: '#000000',
    inputBg: '#ffffff',
    inputBorder: '#c7c7cc',
    accent: '#007AFF',
    timestamp: '#8e8e93',
    tick: '#007AFF',
    separator: 'rgba(0,0,0,0.1)',
    typingDot: '#8e8e93',
    statusBar: '#000000',
  },
  config: {
    myBubbleRadius: '20px 20px 5px 20px',
    theirBubbleRadius: '20px 20px 20px 5px',
    bubblePadding: '10px 14px',
    fontFamily: '-apple-system, "SF Pro Text", system-ui, sans-serif',
    headerLayout: 'center-avatar',
    tickStyle: 'none',
    hasBgPattern: false,
    inputStyle: 'pill',
    avatarSize: '36px',
  },
};

export const imessageDark: ChatTheme = {
  ...imessageLight,
  dark: true,
  vars: {
    chatBg: '#000000',
    headerBg: '#1c1c1e',
    headerText: '#ffffff',
    headerSubtext: '#8e8e93',
    myBubbleBg: '#007AFF',
    myBubbleText: '#ffffff',
    theirBubbleBg: '#2c2c2e',
    theirBubbleText: '#ffffff',
    inputBg: '#1c1c1e',
    inputBorder: '#38383a',
    accent: '#0A84FF',
    timestamp: '#8e8e93',
    tick: '#0A84FF',
    separator: 'rgba(255,255,255,0.08)',
    typingDot: '#8e8e93',
    statusBar: '#ffffff',
  },
};
