import type { ChatTheme } from '@/types';

export const instagramLight: ChatTheme = {
  id: 'instagram',
  name: 'Instagram',
  icon: '📸',
  dark: false,
  vars: {
    chatBg: '#fafafa',
    headerBg: '#ffffff',
    headerText: '#262626',
    headerSubtext: '#8e8e8e',
    myBubbleBg: '#3797f0',
    myBubbleText: '#ffffff',
    theirBubbleBg: '#efefef',
    theirBubbleText: '#262626',
    inputBg: '#efefef',
    inputBorder: 'transparent',
    accent: '#3797f0',
    timestamp: '#8e8e8e',
    tick: '#3797f0',
    separator: 'rgba(0,0,0,0.08)',
    typingDot: '#8e8e8e',
    statusBar: '#262626',
  },
  config: {
    myBubbleRadius: '22px 22px 4px 22px',
    theirBubbleRadius: '22px 22px 22px 4px',
    bubblePadding: '10px 16px',
    fontFamily: '-apple-system, "SF Pro Text", system-ui, sans-serif',
    headerLayout: 'left-avatar',
    tickStyle: 'circle',
    hasBgPattern: false,
    inputStyle: 'pill',
    avatarSize: '44px',
  },
};

export const instagramDark: ChatTheme = {
  ...instagramLight,
  dark: true,
  vars: {
    chatBg: '#000000',
    headerBg: '#000000',
    headerText: '#ffffff',
    headerSubtext: '#8e8e8e',
    myBubbleBg: '#3797f0',
    myBubbleText: '#ffffff',
    theirBubbleBg: '#262626',
    theirBubbleText: '#ffffff',
    inputBg: '#262626',
    inputBorder: 'transparent',
    accent: '#3797f0',
    timestamp: '#8e8e8e',
    tick: '#3797f0',
    separator: 'rgba(255,255,255,0.08)',
    typingDot: '#8e8e8e',
    statusBar: '#ffffff',
  },
};
