import type { ChatTheme } from '@/types';

export const telegramLight: ChatTheme = {
  id: 'telegram',
  name: 'Telegram',
  icon: '✈️',
  dark: false,
  vars: {
    chatBg: '#dae9f5',
    headerBg: '#517da2',
    headerText: '#ffffff',
    headerSubtext: 'rgba(255,255,255,0.7)',
    myBubbleBg: '#efffde',
    myBubbleText: '#000000',
    theirBubbleBg: '#ffffff',
    theirBubbleText: '#000000',
    inputBg: '#ffffff',
    inputBorder: '#dae9f5',
    accent: '#2AABEE',
    timestamp: '#96ab80',
    tick: '#4fae4e',
    separator: 'rgba(0,0,0,0.08)',
    typingDot: '#96ab80',
    statusBar: '#517da2',
  },
  config: {
    myBubbleRadius: '12px 12px 2px 12px',
    theirBubbleRadius: '12px 12px 12px 2px',
    bubblePadding: '8px 12px',
    fontFamily: '"Roboto", system-ui, sans-serif',
    headerLayout: 'left-avatar',
    tickStyle: 'double-tick',
    hasBgPattern: false,
    inputStyle: 'pill',
    avatarSize: '42px',
  },
};

export const telegramDark: ChatTheme = {
  ...telegramLight,
  dark: true,
  vars: {
    chatBg: '#0e1621',
    headerBg: '#17212b',
    headerText: '#ffffff',
    headerSubtext: 'rgba(255,255,255,0.5)',
    myBubbleBg: '#2b5278',
    myBubbleText: '#ffffff',
    theirBubbleBg: '#17212b',
    theirBubbleText: '#ffffff',
    inputBg: '#17212b',
    inputBorder: '#0e1621',
    accent: '#2AABEE',
    timestamp: '#617d8a',
    tick: '#4fae4e',
    separator: 'rgba(255,255,255,0.06)',
    typingDot: '#617d8a',
    statusBar: '#17212b',
  },
};
